services:
  polkamask:
    build:
      context: ./docker
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
      - 8080:8080
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./
          target: /usr/src/app
          action: sync

  dashboard:
    build:
      context: ./dashboard-docker
    environment:
      NODE_ENV: production
    ports:
      - 80:80